jobportal/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('job.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

jobportal/job/urls.py
from django.urls import path
from .views import index, admin_login, user_login, recruiter_login, user_signup, user_home, Logout, recruiter_signup, admin_home,view_users, delete_user, recruiter_pending, change_status,recruiter_accepted,recruiter_rejected, recruiter_all, delete_recruiter, change_passwordadmin,change_passworduser, recruiter_home, change_passwordrecruiter, add_job, job_list, edit_jobdetail, change_companylogo, latest_jobs, user_latestjobs, job_detail, applyforjob,applied_candidatelist,contact

app_name = 'job'
urlpatterns = [
    path('', index, name='index'),    
    path('admin_login', admin_login, name='admin_login'),    
    path('user_login', user_login, name='user_login'),    
    path('recruiter_login', recruiter_login, name='recruiter_login'),    
    path('user_signup', user_signup, name='user_signup'),    
    path('user_home', user_home, name='user_home'),    
    path('recruiter_home', recruiter_home, name='recruiter_home'),    
    path('recruiter_signup', recruiter_signup, name='recruiter_signup'),    
    path('admin_home', admin_home, name='admin_home'),    
    path('view_users', view_users, name='view_users'),   
    path('recruiter_pending', recruiter_pending, name='recruiter_pending'),    
    path('recruiter_accepted', recruiter_accepted, name='recruiter_accepted'),    
    path('recruiter_rejected', recruiter_rejected, name='recruiter_rejected'),    
    path('recruiter_all', recruiter_all, name='recruiter_all'),    
    path('delete_user/<int:pid>', delete_user, name='delete_user'),    
    path('delete_recruiter/<int:pid>', delete_recruiter, name='delete_recruiter'),    
    path('change_status/<int:pid>', change_status, name='change_status'),    
    path('change_passwordadmin', change_passwordadmin, name='change_passwordadmin'),    
    path('change_passworduser', change_passworduser, name='change_passworduser'),    
    path('change_passwordrecruiter', change_passwordrecruiter, name='change_passwordrecruiter'),    
    path('applied_candidatelist', applied_candidatelist, name='applied_candidatelist'),  
    path('contact', contact, name='contact'),      
    path('add_job', add_job, name='add_job'),    
    path('job_list', job_list, name='job_list'), 
    path('latest_jobs', latest_jobs, name='latest_jobs'), 
    path('user_latestjobs', user_latestjobs, name='user_latestjobs'), 
    path('job_detail/<int:pid>', job_detail, name='job_detail'), 
    path('applyforjob/<int:pid>', applyforjob, name='applyforjob'), 
    path('edit_jobdetail/<int:pid>', edit_jobdetail, name='edit_jobdetail'),       
    path('change_companylogo/<int:pid>', change_companylogo, name='change_companylogo'),       
    path('Logout', Logout, name='Logout'),    
]

jobportal/job/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model

# Create your models here.

class StudentUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=15, null=True)
    # image = models.ImageField(upload_to = "images")
    image = models.FileField(null=True)
    gender = models.CharField(max_length=10, null=True)
    type = models.CharField(max_length=15, null=True)

    def __str__(self):
        return self.user.username

class Recruiter(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=15, null=True)
    # image = models.ImageField(upload_to = "images")
    image = models.FileField(null=True)
    gender = models.CharField(max_length=10, null=True)
    company = models.CharField(max_length=100, null=True)
    type = models.CharField(max_length=15, null=True)
    status = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.user.username

class Job(models.Model):
    recruiter = models.ForeignKey(Recruiter,on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    title = models.CharField(max_length=100)
    salary = models.FloatField(max_length=20)
    image = models.FileField()
    description = models.CharField(max_length=300)
    experience = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    skills = models.CharField(max_length=100)
    creationdate = models.DateField()

    def __str__(self):
        return self.title

class Apply(models.Model):
    job = models.ForeignKey(Job,on_delete=models.CASCADE)
    student = models.ForeignKey(StudentUser, on_delete=models.CASCADE)
    resume = models.FileField(null=True)
    applydate = models.DateField()
    
    def __str__(self):
        return self.id

jobportal/job/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import *
from datetime import date
# Create your views here.

def index(request):
    return render(request, 'job/index.html')

def admin_login(request):
    error = ''
    if request.method == 'POST':
        u = request.POST.get('uname')
        p = request.POST.get('pwd')
        user = authenticate(username =u, password=p)
        print(u,p)
        try:
            if user.is_staff:
                login(request,user)
                error = 'no'
            else:
                error = 'yes'
        except:
            error = 'yes'
    
    d = {'error':error}

    return render(request, 'job/admin_login.html',d)

def user_login(request):
    error = ""
    if request.method == 'POST':
        u = request.POST.get('uname')
        p = request.POST.get('pwd')
        user = authenticate(username = u, password = p)
        if user:
            try:
                user1 = StudentUser.objects.get(user = user)
                if user1.type == 'student':
                    login(request,user)
                    error = 'no'
                    # return render(request, 'job/user_home.html')
                else:
                    error = 'yes'
            except:
                error = 'yes'
        else:
            error = 'yes'
    
    d = {'error' :error}
   
    return render(request, 'job/user_login.html', d)

def recruiter_login(request):
    error = ""
    if request.method == 'POST':
        u =  request.POST.get('uname')
        p =  request.POST.get('pwd')
        user = authenticate(username = u, password = p)
        if user:
            try:
                user1 = Recruiter.objects.get(user = user)
                print(user1.status)
                if user1.type == 'recruiter' and user1.status != 'pending':
                    login(request,user)
                    error = 'no'
                    # return render(request, 'job/user_home.html')
                else:
                    error = 'not'
            except:
                error = 'yes'
        else:
            error = 'yes'
    
    d = {'error' :error}
    print(error)
    return render(request, 'job/recruiter_login.html',d)

def recruiter_signup(request):
    error = ''

    if request.method == 'POST':
        f = request.POST.get('fname')
        l = request.POST.get('lname')
        i = request.FILES.get('image')
        p = request.POST.get('pwd')
        e = request.POST.get('email')
        con = request.POST.get('contact')
        gen = request.POST.get('gender')
        company = request.POST.get('company')
        try:
            user = User.objects.create_user(first_name = f,last_name = l,username=e, password = p)
            Recruiter.objects.create(user=user,mobile=con,image=i,gender=gen,company=company,type='recruiter',status='pending')
            error = 'no'
        except:
            error = 'yes'
    d = {'error' : error}

    return render(request, 'job/recruiter_signup.html',d)

def user_signup(request):
    error = ''

    if request.method == 'POST':
        f = request.POST.get('fname')
        l = request.POST.get('lname')
        i = request.FILES.get('image')
        p = request.POST.get('pwd')
        e = request.POST.get('email')
        con = request.POST.get('contact')
        gen = request.POST.get('gender')
        try:
            user = User.objects.create_user(first_name = f,last_name = l,username=e, password = p)
            StudentUser.objects.create(user=user,mobile=con,image=i,gender=gen,type='student')
            error = 'no'
        except:
            error = 'yes'
    d = {'error' : error}
    return render(request, 'job/user_signup.html', d)


def view_users(request):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    data = StudentUser.objects.all()
    d = {'data':data}
    return render(request, 'job/view_users.html',d)

def delete_user(request,pid):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    student = User.objects.get(id=pid)
    student.delete()
    return redirect('job:view_users')

def delete_recruiter(request,pid):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    recruiter = User.objects.get(id=pid) 
    print(recruiter) 
    recruiter.delete()
    return redirect('job:recruiter_all')


def recruiter_pending(request):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    data = Recruiter.objects.filter(status='pending')
    d = {'data':data}

    return render(request, 'job/recruiter_pending.html',d)

def change_status(request,pid):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    error = ''
    recruiter = Recruiter.objects.get(id=pid)
    if request.method == 'POST':
        s = request.POST.get('status')
        recruiter.status = s
        try:
            recruiter.save()
            error = 'no'
        except:
            error = 'yes'

    d = {'recruiter':recruiter, 'error':error}

    return render(request, 'job/change_status.html',d)

def change_passwordadmin(request):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    error = ''
    if request.method == 'POST':
        c = request.POST.get('currentpassword')
        n = request.POST.get('newpassword')
        try:
            u = User.objects.get(id=request.user.id)
            if u.check_password(c):
                u.set_password(n)
                u.save()
                error = 'no'
            else:
                error = 'not'
        except:
            error = 'yes'

    d = {'error':error}

    return render(request, 'job/change_passwordadmin.html',d)

def change_passworduser(request):
    if not request.user.is_authenticated:
        return redirect('job:user_login')

    error = ''
    if request.method == 'POST':
        c = request.POST.get('currentpassword')
        n = request.POST.get('newpassword')
        try:
            u = User.objects.get(id=request.user.id)
            if u.check_password(c):
                u.set_password(n)
                u.save()
                error = 'no'
            else:
                error = 'not'
        except:
            error = 'yes'

    d = {'error':error}

    return render(request, 'job/change_passworduser.html',d)

def change_passwordrecruiter(request):
    if not request.user.is_authenticated:
        return redirect('job:recruiter_login')

    error = ''
    if request.method == 'POST':
        c = request.POST.get('currentpassword')
        n = request.POST.get('newpassword')
        try:
            u = User.objects.get(id=request.user.id)
            if u.check_password(c):
                u.set_password(n)
                u.save()
                error = 'no'
            else:
                error = 'not'
        except:
            error = 'yes'

    d = {'error':error}

    return render(request, 'job/change_passwordrecruiter.html',d)


def recruiter_accepted(request):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    data = Recruiter.objects.filter(status='Accept')
    d = {'data':data}

    return render(request, 'job/recruiter_accepted.html',d)

def recruiter_rejected(request):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    data = Recruiter.objects.filter(status='Reject')
    d = {'data':data}

    return render(request, 'job/recruiter_rejected.html',d)

def recruiter_all(request):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')

    data = Recruiter.objects.all()
    d = {'data':data}

    return render(request, 'job/recruiter_all.html',d)

def recruiter_home(request):
    if not request.user.is_authenticated:
        return redirect('job:recruiter_login')

    user = request.user
    recruiter = Recruiter.objects.get(user=user)

    error = ''

    if request.method == 'POST':
        f = request.POST.get('fname')
        l = request.POST.get('lname')
        con = request.POST.get('contact')
        gen = request.POST.get('gender')

        recruiter.user.first_name = f
        recruiter.user.last_name = l
        recruiter.mobile = con
        recruiter.gender = gen

        try:
            recruiter.save()
            recruiter.user.save()
            error = 'no'
        except:
            error = 'yes'
       
        i = request.FILES.get('image')       
        if i and i != None:           
            recruiter.image = i
            recruiter.save()
            error = 'no'
        

    d = {'recruiter':recruiter, 'error':error}
    return render(request, 'job/recruiter_home.html',d)


def user_home(request):
    if not request.user.is_authenticated:
        return redirect('job:user_login')

    user = request.user
    student = StudentUser.objects.get(user=user)

    error = ''

    if request.method == 'POST':
        f = request.POST.get('fname')
        l = request.POST.get('lname')
        con = request.POST.get('contact')
        gen = request.POST.get('gender')

        student.user.first_name = f
        student.user.last_name = l
        student.mobile = con
        student.gender = gen

        try:
            student.save()
            student.user.save()
            error = 'no'
        except:
            error = 'yes'
       
        i = request.FILES.get('image')       
        if i and i != None:           
            student.image = i
            student.save()
            error = 'no'
        

    d = {'student':student, 'error':error}
    
    return render(request, 'job/user_home.html',d)


def admin_home(request):
    if not request.user.is_authenticated:
        return redirect('job:admin_login')
    
    rcount = Recruiter.objects.all().count()

jobportal/job/templates/job/admin_home.html
{% load static %}

{% block body %}

{% include 'job/admin_navigation.html' %}

<style>
    .mydiv:hover{
        box-shadow: 0 0 20px 0 rgba(0,0,0,0.3);
        transform: translateY(-20px);
    }
</style>

<marquee behavior="" direction="" style="font-family: cursive; font-size: 25px; color: darkcyan;background-color: black; font-weight: bold; margin-top: 1%;">
    Contact Us
</marquee>

<hr>

<div class="container mt-5">
    <br>
    <br>
    <div class="row mt-5">
        <div class="col-sm-6 mydiv">
            <h4 class="text-center"><i class="fa fa-user mr-2"></i>Total Recruiters</h4>
            <p class="text-center font-weight-bold">{{rcount}}</p>
        </div>
        <div class="col-sm-6 mydiv">
            <h4 class="text-center"><i class="fa fa-users mr-2"></i>Total Users</h4>
            <p class="text-center font-weight-bold">{{scount}}</p>
        </div>
        
    </div>
</div>


{% endblock body %}

jobportal/job/templates/job/applyforjob.html
{% load static %}

{% block body %}

{% include 'job/user_navigation.html' %}

<style>
    tr{
        text-align: center;
    }
</style>

<marquee behavior="" direction="" style="font-family: cursive; font-size: 25px; color: darkcyan;background-color: black; font-weight: bold; margin-top: 1%;">
    Apply For Job
</marquee>

<hr>

<div class="container shadow-lg py-2 mb-2"> 
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <label class="font-weight-bold">Upload Resume</label>
            <input type="file" class="form-control" name="resume">
        </div>
        <input type="submit" value="submit" class="btn btn-danger mt-3">
    </form>
</div>

{% ifequal error 'close' %}
    <script>
        alert("Sorry, last date is over!!!")
        window.location.replace("{% url 'job:user_latestjobs' %}");
    </script>
{% endifequal %}


{% ifequal error 'notopen' %}
    <script>
        alert("Sorry, Application Line is not open!!!")
        window.location.replace("{% url 'job:user_latestjobs' %}");
    </script>
{% endifequal %}


{% ifequal error 'done' %}
    <script>
        alert("Job Application Submitted successfully :)")
        window.location.replace("{% url 'job:user_latestjobs' %}");
    </script>
{% endifequal %}


{% endblock body %}

jobportal/job/templates/job/change_passworduser.html
{% load static %}

{% block body %}

{% include 'job/user_navigation.html' %}

<script>
    function checkpass(){
        if(document.changepassword.newpassword.value != document.changepassword.confirmpassword.value){
            alert("new password and confirm password field does not match!!!!");
            document.changepassword.confirmpassword.focus();
            return false;
        }
    }
</script>

<marquee behavior="" direction="" style="font-family: cursive; font-size: 25px; color: darkcyan;background-color: black; font-weight: bold; margin-top: 1%;">
    Change User Password
</marquee>

<hr>

<form action="" method="POST" class="container mt-5" name="changepassword" onsubmit="return checkpass()">
    {% csrf_token %}
    <label for=""><b>Current Password</b></label>
    <input type="Password" class="form-control" name="currentpassword" required="true">

    <label for=""><b>New Password</b></label>
    <input type="Password" class="form-control" name="newpassword" required="true">

    <label for=""><b>Confirm New Password</b></label>
    <input type="Password" class="form-control" name="confirmpassword" required="true">

    <input type="submit" class="btn btn-primary" style="margin-top: 2%; color: darkcyan; background-color: black; height: 40px;">
</form>

{% include 'job/footer.html' %}

{% ifequal error 'no' %}
    <script>
        alert("your password updated successfully!")
        window.location.replace("{% url 'job:Logout' %}");
    </script>
{% endifequal %}

{% ifequal error 'yes' %}
    <script>
        alert("something went wrong, try again ....");
    </script>
{% endifequal %}

{% ifequal error 'not' %}
    <script>
        alert("your current password is wrong");
    </script>
{% endifequal %}

{% endblock body %}

jobportal/job/templates/job/job_detail.html
{% load static %}

{% block body %}

{% include 'job/user_navigation.html' %}

<style>
    tr{
        text-align: center;
    }
</style>

<marquee behavior="" direction="" style="font-family: cursive; font-size: 25px; color: darkcyan;background-color: black; font-weight: bold; margin-top: 1%;">
    Job Detail
</marquee>

<hr>

<div class="container shadow-lg py-2 mb-2"> 
    <div class="row">
        <div class="col-md-4">
            <img src="{{job.image.url}}" style="width:300px; height:200px;">
        </div>
        <div class="col-md-6">
            <h2>{{job.title}}</h2>
            <p>{{job.recruiter.company}}<em><a href="{% url 'job:user_latestjobs' %}">(View All Jobs)</a></em></p>
            <a href="" class="mr-2"><i class="fa fa-map-marker mr-2"></i>{{job.location}}</a> 
            <a href=""><i class="fa fa-calendar mr-2"></i>{{job.creationdate}}</a>
            <br>
            <strong><i class="fa fa-money mr-2 mt-2"></i>{{job.salary}}</strong>
            <div class="mt-4">
                <a href="{% url 'job:applyforjob' job.id %}" type="submit" class="btn btn-danger" style="width: 200px; height: 40px;">
                    Apply For This Job
                </a>
            </div>
        </div>
    </div>

    <div class="mt-3">
        <h4>OverView</h4>
        <p>{{job.description}}</p>

        <h4>Required Experience</h4>
        <p>{{job.experience}}</p>

        <h4>Skills Required</h4>
        <p>{{job.skills}}</p>

        <h4>Start Date For Applying</h4>
        <p>{{job.start_date}}</p>

        <h4>End Date For Applying</h4>
        <p>{{job.end_date}}</p>

    </div>

</div>

{% endblock body %}

jobportal/job/templates/job/recruiter_accepted.html
{% load static %}

{% block body %}

{% include 'job/admin_navigation.html' %}

<marquee behavior="" direction="" style="font-family: cursive; font-size: 25px; color: darkcyan;background-color: black; font-weight: bold; margin-top: 1%;">
    View Recruiter - Accepted
</marquee>

<hr>

<div class="container">
    <table id="example" class="table table-hover ">
        <thead>
            <tr style="background-color: #000080; color: white;">
                <th>S.No.</th>
                <th>Full Name</th>
                <th>Email ID</th>
                <th>Contact</th>
                <th>Gender</th>
                <th>Company</th>
                <th>Image</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
                <tr style="background-color: #DEB887;">
                    <td>{{forloop.counter}}</td>
                    <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                    <td>{{i.user.username}}</td>
                    <td>{{i.mobile}}</td>
                    <td>{{i.gender}}</td>
                    <td>{{i.company}}</td>
                    <td><img src="{{i.image.url}}" alt="Nothing" style="width: 100px; height: 100px;border-radius: 50%;"></td>
                    <td>{{i.status}}</td>
                    <td><a href="{% url 'job:change_status' i.id%}" class="btn btn-success btn-sm" >Change Status</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock body %}

jobportal/job/templates/job/recruiter_login.html
{% load static %}

{% block body %}

{% include 'job/navigation.html' %}

<marquee behavior="" direction="" style="font-family: cursive; font-size: 25px; color: darkcyan;background-color: black; font-weight: bold; margin-top: 1%;">
    Recruiter Login
</marquee>

<hr>

<form action="" method="POST" class="container mt-5">
    {% csrf_token %}
    <label for=""><b>Email ID</b></label>
    <input type="email" class="form-control" name="uname" placeholder="Enter Email ID">
    <label for=""><b>Password</b></label>
    <input type="password" class="form-control" name="pwd" placeholder="Enter Password">
    <input type="submit" class="btn btn-primary" style="margin-top: 2%; color: darkcyan; background-color: black; height: 40px;">
    <a href="{% url 'job:recruiter_signup' %}" class="btn btn-primary" style="margin-top: 2%; color: darkcyan; background-color: black; height: 40px;">CREATE AN ACCOUNT</a>
</form>

{% include 'job/footer.html' %}

{% ifequal error 'no' %}
    <script>
        alert("Login successful!")
        window.location.replace("{% url 'job:recruiter_home' %}");
    </script>
{% endifequal %}

{% ifequal error 'yes' %}
    <script>
        alert("Invalid login credentials, try again ....");
    </script>
{% endifequal %}


{% endblock body %}

jobportal/job/templates/job/recruiter_navigation.html
<html>
    <head>
        {% load static %}
        <title>Job Portal</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <style>
            .nav-link{
                color: white !important;
                margin-right: 4px;
            }
            .nav-link:hover{
                color: yellow !important;
                /* font-weight: bold; */
                background-color: red;
                border-radius: 10px;
            }
            .navbar-brand:hover{
                color: yellow !important;
            }
        </style>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <img src="{% static 'job/images/download.jpeg' %}" width="180px;" height="150px;">
                </div>
                <div class="col-sm-6 mt-5 text-center">
                    <span style="font-weight: bold; font-size: 30px;">
                        <span style="color:red;">Online Job</span>
                        <span style="color:green;">Portal System</span>
                    </span>
                </div>
                <div class="col-sm-3 mt-5" style="padding-left: 10%;">
                    <span style="font-weight: bold; font-size: 30px;">
                        <span><i class="fa fa-twitter pl-1"></i></span>
                        <span><i class="fa fa-linkedin pl-1"></i></span>
                        <span><i class="fa fa-instagram pl-1"></i></span>
                        <span><i class="fa fa-telegram pl-1"></i></span>
                    </span>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-sm" style="background-color: maroon;">
            <a href="" class="navbar-brand text-white pl-5 font-weight-bold" style="font-family: cursive; font-size: 25px;">Job Portal</a>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'job:recruiter_home' %}" class="nav-link" style="margin-left: 280px;;"><i class="fa fa-home mr-1"></i>Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'job:add_job' %}" class="nav-link"><i class="fa fa-plus-circle mr-1"></i>Add Job</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'job:job_list' %}" class="nav-link"><i class="fa fa-list-ol mr-1"></i>Job List</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'job:applied_candidatelist' %}" class="nav-link"><i class="fa fa-list-ol mr-1"></i>Candidate Applied</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'job:change_passwordrecruiter' %}" class="nav-link"><i class="fa fa-user-circle mr-1"></i>Change Password</a>
                </li>                
                <li class="nav-item">
                    <a href="{% url 'job:Logout' %}" class="nav-link"><i class="fa fa-sign-out mr-1"></i>Logout</a>
                </li>
            </ul>
            <a href="" class="navbar-brand text-white pl-5 font-weight-bold" style="font-family: cursive; font-size: 18px;">{{request.user.first_name}}</a>

        </nav>

    </body>
</html>

jobportal/job/templates/job/user_navigation.html
<html>
    <head>
        {% load static %}
        <title>Job Portal</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <style>
            .nav-link{
                color: white !important;
                margin-right: 4px;
            }
            .nav-link:hover{
                color: yellow !important;
                /* font-weight: bold; */
                background-color: red;
                border-radius: 10px;
            }
            .navbar-brand:hover{
                color: yellow !important;
            }
        </style>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <img src="{% static 'job/images/download.jpeg' %}" width="180px;" height="150px;">
                </div>
                <div class="col-sm-6 mt-5 text-center">
                    <span style="font-weight: bold; font-size: 30px;">
                        <span style="color:red;">Online Job</span>
                        <span style="color:green;">Portal System</span>
                    </span>
                </div>
                <div class="col-sm-3 mt-5" style="padding-left: 10%;">
                    <span style="font-weight: bold; font-size: 30px;">
                        <span><i class="fa fa-twitter pl-1"></i></span>
                        <span><i class="fa fa-linkedin pl-1"></i></span>
                        <span><i class="fa fa-instagram pl-1"></i></span>
                        <span><i class="fa fa-telegram pl-1"></i></span>
                    </span>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-sm" style="background-color: maroon;">
            <a href="" class="navbar-brand text-white pl-5 font-weight-bold" style="font-family: cursive; font-size: 25px;">Job Portal</a>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'job:user_home' %}" class="nav-link" style="margin-left: 280px;;"><i class="fa fa-home mr-1"></i>Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'job:user_latestjobs' %}" class="nav-link"><i class="fa fa-users mr-1"></i>Job List</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'job:change_passworduser' %}" class="nav-link"><i class="fa fa-user-circle mr-1"></i>Change Password</a>
                </li>                
                <li class="nav-item">
                    <a href="{% url 'job:Logout' %}" class="nav-link"><i class="fa fa-sign-out mr-1"></i>Logout</a>
                </li>
            </ul>
            <a href="" class="navbar-brand text-white pl-5 font-weight-bold" style="font-family: cursive; font-size: 20px;">{{request.user.first_name}}</a>
        </nav>

    </body>
</html>